version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            apt update -y
            apt install -y build-essential
      - run:
          name: Test
          command: |
            cd test
            make
            ./test

