version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: apt update -y
      - run: apt install -y build-essential
      - run: cd test && make run

